plugins {
    id 'dev.architectury.loom' version '1.10.455'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group
base { archivesName = project.archives_base_name }

loom {
    forge { }
    runs {
        data {
            data()
            programArgs '--mod', 'loot_bag', '--all', '--output', file('example').absolutePath,
                    '--existing', file('src/main/resources').absolutePath
        }
    }
}

repositories { mavenLocal() }

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    forge "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"
}

processResources {
    inputs.property 'version', project.version
    filesMatching('META-INF/mods.toml') { expand version: project.version }
}

tasks.withType(JavaCompile).configureEach { options.release = 17 }
java {
    toolchain.languageVersion = JavaLanguageVersion.of(17)
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}
tasks.withType(JavaExec).configureEach {
    javaLauncher = javaToolchains.launcherFor { languageVersion = JavaLanguageVersion.of(17) }
}
jar { from('LICENSE') { rename { "${it}_${project.base.archivesName.get()}" } } }
tasks.withType(Jar).configureEach { exclude '.cache/**' }
tasks.named('runData') { dependsOn tasks.named('downloadAssets') }
tasks.named('sourcesJar') { mustRunAfter tasks.named('runData') }


publishing {
    publications {
        mavenJava(MavenPublication) { from components.java }
    }
    repositories { mavenLocal() }
}
